server:
  port: 8080

spring:
  flyway:
    url: jdbc:mysql://localhost:33306/webflux_r2dbc_sample?useSSL=false
    user: root
    password: password
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:mysql://localhost:33306/webflux_r2dbc_sample?useSSL=false
    username: root
    password: password
